"""Migration

Revision ID: 4b7aa7ab2934
Revises: 7ffa182f60ed
Create Date: 2021-08-26 16:58:35.684573

"""

# revision identifiers, used by Alembic.
revision = '4b7aa7ab2934'
down_revision = '7ffa182f60ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('service', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'service')
    # ### end Alembic commands ###
