"""Migration

Revision ID: a306d9c4421a
Revises: 4b7aa7ab2934
Create Date: 2021-08-26 17:00:55.585218

"""

# revision identifiers, used by Alembic.
revision = 'a306d9c4421a'
down_revision = '4b7aa7ab2934'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('dat', sa.DateTime(timezone=255), nullable=True))
    op.drop_column('sessions', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('date', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'dat')
    # ### end Alembic commands ###
