"""Migration

Revision ID: e77599140f89
Revises: 35f8268af583
Create Date: 2021-08-26 18:50:07.946240

"""

# revision identifiers, used by Alembic.
revision = 'e77599140f89'
down_revision = '35f8268af583'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('del',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarehe', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('del')
    # ### end Alembic commands ###
